name: Deploy production app

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - name: Check out code
      uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Recover Gradle cache
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
    - name: Build release app
      run: ./gradlew assembleRelease
    - name: Publish artefact
      uses: actions/upload-artifact@v1
      with:
        name: app-release
        path: app/build/outputs/apk/release/covid19-cz-release.apk
    - name: Upload app to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1.1.1
      with:
        appId: 1:1077972356575:android:27fb3236d490d49361886a
        token: ${{ secrets.FIREBASE_TOKEN }}
        groups: internal-test
        path: app/build/outputs/apk/release/covid19-cz-release.apk